version: '3.9'
services:
  api:
    image: $SCRAPER_IMAGE
    command: bash -c 'npm i && npm run start:dev'
    container_name: $SCRAPER_CONTAINER_NAME
    ports:
      - $SCRAPER_PORT:$SCRAPER_PORT
    env_file:
      - .env
    working_dir: $SCRAPER_WORKING_DIR
    volumes:
      - .:$SCRAPER_WORKING_DIR