export const CATEGORIES = {
  aditivos: '22/aditivos',
  'articulos-plasticos-descartables': '2/articulos-plasticos-descartables',
  'bolsas-plasticas': '3/bolsas-plasticas',
  'botellas-de-pet': '4/botellas-de-pet',
  'cajas-plasticas': '47/cajas-plasticas',
  'compuestos-de-pvc': '24/compuestos-de-pvc',
  embalajes: '50/embalajes',
  energia: '82/energia',
  'envases-plasticos': '6/envases-plasticos',
  envolturas: '7/envolturas',
  extrusoras: '17/extrusoras',
  inyectoras: '18/inyectoras',
  masterbatch: '25/masterbatch',
  moldes: '19/moldes',
  perifericos: '10/perifericos',
  polimeros: '71/polimeros',
  'preformas-pet': '55/preformas-pet',
  recicladoras: '85/recicladoras',
  resinas: '27/resinas',
  sopladoras: '21/sopladoras',
};